// <auto-generated />
using DomingoRoofWorks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DomingoRoofWorks.Migrations
{
    [DbContext(typeof(Domingo_Roof_WorksContext))]
    [Migration("20210706152514_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomingoRoofWorks.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength(true);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Job", b =>
                {
                    b.Property<int>("JobCardId")
                        .HasColumnType("int")
                        .HasColumnName("JobCardID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int")
                        .HasColumnName("JobTypeID");

                    b.HasKey("JobCardId")
                        .HasName("PK__Job__98F41DDF3D847537");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.JobEmployee", b =>
                {
                    b.Property<int>("JobEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobEmployeeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("EmployeeID");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int")
                        .HasColumnName("JobCardID");

                    b.HasKey("JobEmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobCardId");

                    b.ToTable("Job_Employee");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.JobMaterial", b =>
                {
                    b.Property<int>("JobMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobMaterialID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobCardId")
                        .HasColumnType("int")
                        .HasColumnName("JobCardID");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("JobMaterialId");

                    b.HasIndex("JobCardId");

                    b.HasIndex("MaterialId");

                    b.ToTable("Job_Material");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.JobType", b =>
                {
                    b.Property<int>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobType1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("JobType");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobType");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("MaterialId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Job", b =>
                {
                    b.HasOne("DomingoRoofWorks.Models.Customer", "Customer")
                        .WithMany("Jobs")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Job__CustomerID__3E52440B")
                        .IsRequired();

                    b.HasOne("DomingoRoofWorks.Models.JobType", "JobType")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTypeId")
                        .HasConstraintName("FK__Job__JobTypeID__3F466844")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.JobEmployee", b =>
                {
                    b.HasOne("DomingoRoofWorks.Models.Employee", "Employee")
                        .WithMany("JobEmployees")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__Job_Emplo__Emplo__4316F928")
                        .IsRequired();

                    b.HasOne("DomingoRoofWorks.Models.Job", "JobCard")
                        .WithMany("JobEmployees")
                        .HasForeignKey("JobCardId")
                        .HasConstraintName("FK__Job_Emplo__JobCa__4222D4EF")
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.JobMaterial", b =>
                {
                    b.HasOne("DomingoRoofWorks.Models.Job", "JobCard")
                        .WithMany("JobMaterials")
                        .HasForeignKey("JobCardId")
                        .HasConstraintName("FK__Job_Mater__JobCa__46E78A0C")
                        .IsRequired();

                    b.HasOne("DomingoRoofWorks.Models.Material", "Material")
                        .WithMany("JobMaterials")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__Job_Mater__Mater__47DBAE45")
                        .IsRequired();

                    b.Navigation("JobCard");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Customer", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Employee", b =>
                {
                    b.Navigation("JobEmployees");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Job", b =>
                {
                    b.Navigation("JobEmployees");

                    b.Navigation("JobMaterials");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.JobType", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("DomingoRoofWorks.Models.Material", b =>
                {
                    b.Navigation("JobMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
